name: Tests

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Run Tests
      run: dotnet test
      shell: pwsh
